package net.transgressoft.musicott.splash;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;
import java.util.function.Supplier;

/**
 * Reads the build version string from {@code /META-INF/build-info.properties} on the
 * classpath, without requiring Spring's {@code BuildProperties} bean.
 *
 * <p>The startup splash needs the version label populated before Spring constructs
 * its {@code ApplicationContext}; the {@code BuildProperties} bean is only available
 * after Spring boots, which is too late for the splash. Both the splash and
 * {@code AboutWindowAlert} ultimately read the same {@code build-info.properties}
 * file generated by Gradle's {@code springBoot { buildInfo() }} task.
 *
 * <p>When the resource is missing — typically an IDE invocation that bypassed
 * {@code gradle processResources} — the reader returns {@code "dev"} rather than
 * throwing, mirroring {@code AboutWindowAlert}'s nullable-{@code BuildProperties}
 * fallback.
 */
public final class BuildVersionReader {

    private static final Logger logger = LoggerFactory.getLogger(BuildVersionReader.class);

    private static final String BUILD_INFO_RESOURCE = "/META-INF/build-info.properties";
    private static final String VERSION_KEY = "build.version";
    private static final String FALLBACK_VERSION = "dev";

    private BuildVersionReader() {
        // utility class
    }

    /**
     * Reads {@code build.version} from {@code /META-INF/build-info.properties} on the
     * classpath of {@code BuildVersionReader} itself.
     *
     * @return the version string, or {@code "dev"} if the resource is missing or the
     *         key is absent
     */
    public static String read() {
        return read(() -> BuildVersionReader.class.getResourceAsStream(BUILD_INFO_RESOURCE));
    }

    /**
     * Reads {@code build.version} from the {@link InputStream} produced by the supplier.
     *
     * <p>Package-private so unit tests can inject a deterministic missing-resource
     * scenario without manipulating the real classpath.
     */
    static String read(Supplier<InputStream> sourceSupplier) {
        try (InputStream in = sourceSupplier.get()) {
            if (in == null) {
                logger.warn("Build info resource {} not found on classpath; falling back to '{}'",
                    BUILD_INFO_RESOURCE, FALLBACK_VERSION);
                return FALLBACK_VERSION;
            }
            Properties props = new Properties();
            props.load(in);
            String version = props.getProperty(VERSION_KEY);
            if (version == null || version.isBlank()) {
                logger.warn("Build info resource {} present but key '{}' missing; falling back to '{}'",
                    BUILD_INFO_RESOURCE, VERSION_KEY, FALLBACK_VERSION);
                return FALLBACK_VERSION;
            }
            return version;
        } catch (IOException e) {
            logger.warn("Failed to read {}; falling back to '{}'", BUILD_INFO_RESOURCE, FALLBACK_VERSION, e);
            return FALLBACK_VERSION;
        }
    }
}
